[metadata]
addr = 0x664
size = 0x89
last_change = 2024-03-09T19:23:47.659894Z

[header]
last_change = 2024-03-09T19:23:47.659894Z
name = "fish_thenticate"
addr = 0x664

[stack_vars.-0x18]
last_change = 2024-03-09T19:23:38.850658Z
offset = -24
name = "fish_buff"
type = "char[12]"
size = 0xc
addr = 0x664

[header.args.1]
offset = 0x1
name = "fish_password"
size = 0x8
