[metadata]
addr = 0x71d
size = 0xb8
last_change = 2024-03-09T19:26:53.894012Z

[header]
last_change = 2024-03-09T19:26:53.894604Z
name = "main"
addr = 0x71d
type = "int"

[stack_vars.-0x2c]
offset = 0x1c
name = "rc"
type = "int"
size = 0x4
addr = 0x71d

[stack_vars.-0x28]
offset = 0x20
name = "username"
type = "char[16]"
size = 0x10
addr = 0x71d

[stack_vars.-0x18]
offset = 0x30
name = "auth"
type = "char[16]"
size = 0x10
addr = 0x71d

[header.args.0]
offset = 0x0
name = "argc"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "argv"
type = "const char **"
size = 0x8

[header.args.2]
offset = 0x2
name = "password"
type = "const char **"
size = 0x8
