[metadata]
addr = 0x664
size = 0x89
last_change = 2024-03-09T19:17:42.829138Z

[header]
last_change = 2024-03-09T19:17:42.829138Z
name = "frq_thenticate"
addr = 0x664
type = "_BOOL8"

[header.args.1]
offset = 0x1
name = "password"
size = 0x8
