user = "frqmod"
version = "4.0.0"
last_push_time = 2024-03-09T19:17:14.377485Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: _BOOL8 frq_thenticate(args=0); @0x664>"
