user = "ghidra_user"
version = "4.1.6"
last_push_time = 2024-04-22T00:32:11.999325Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: char mahaloz_main(args=3); @0x71d vars=2 len=0xb8> from mahaloz"
