[metadata]
name = "mahaloz_struct"
size = 0xc
last_change = 2024-03-09T19:03:07.341653Z

[members.0x0]
name = "field_0"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4
