[metadata]
name = "mahaloz_struct"
size = 0x10
last_change = 2024-03-09T19:03:17.405989Z

[members.0x0]
name = "s1"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "s2"
offset = 0x4
type = ""
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4

[members.0xc]
name = "field_C"
offset = 0xc
type = ""
size = 0x4
